### ISSUE TITLE
alliance members can demolish all embassies

### ISSUE THREAD

**Issue by fireartist** [plainblack/Lacuna-Server-Open#215]
An alliance member (not the leader) can demolish any and all embassies, and still remain in their alliance.
I don't think simply checking they have at least 1 colony with an Embassy would be sufficient.
I think we really need to require an Embassy on an empire's homeworld, to ensure they don't abandon / lose their only planet with an embassy.
And if they're in an alliance, they should not be able to change their homeworld unless the new planet already has an embassy.

**Comment by dmcbride** [comment]
Empire stats now return the building ID of the highest level non-flat embassy, so that scripts can easily find an embassy to vote at.  Alliance leaders can demolish spare embassies, and can downlevel their highest embassy as long as they still have room for all the allies currently in the alliance.  Parliament voting can now be done via embassy, though it can also still be done via parliaments for now.

No new column added to the empire.

Given the additional functionality found in the embassy, and the public direction of eliminating parliament buildings, I think we can close this.
