### ISSUE TITLE
UI incorrectly prompts to downgrade a building

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Server-Open#281]
Summary. Downgrading a Space Station module can also prompt to downgrade the last building you viewed.

To Reproduce:
Navigate to a planet.
Click a building (say the Embassy)
(With or without closing the building view) Navigate to a Space Station
Click a module (say a warehouse)
Click 'Downgrade'.
A prompt is displayed 'Do you want to downgrade your level 30 Embassy)
(Click 'no')
Followed by the (correct) 'Do you want to downgrade your level 5 Warehouse)

**Comment by 1vasari** [comment]
I'm going to leave this to be fixed in the new UI. For two reasons:

1. It's fairly obscure. I've noticed this myself once and never seen anyone complain about it.
2. The current code is very complex in the way that data gets passed around. When that part of the UI gets moved over to using React and Reflux this issue will likely just disappear by itself due to the simplified data flow that can be implemented using the aforementioned libraries.

**Comment by 1vasari** [comment]
This issue is now being tracked at https://github.com/plainblack/Lacuna-Web-Client/issues/110
