### ISSUE TITLE
Disallow planet names starting with "#"

### ISSUE THREAD

**Issue by tmtowtdi** [plainblack/Lacuna-Server-Open#330]
This is a most-likely low priority enhancement request.

If it's feasible (mainly meaning "if there aren't already too many planets already out there whose names start with a #"), it might be nice to dissallow such names.

I'm not sure how much impact it'd have on the browser client, but it'd be nice for scripts to be able to allow a "--planet" argument that can be either the planet's name or its ID.  Right now, there's no way to distinguish between the two, since naming your planet "123456" is perfectly valid, as is naming it "#123456".

If "#" were disallowed as the first character of a planet name, it'd always be clear to a script that "--planet #123456" was referring to a planet ID, not a name.

**Comment by icydee** [comment]
Not sure why this needs a change to the server code. Easy enough to write a script that takes either --planet (for it's name) or --planet_id (for it's ID).

**Comment by RedOrion** [comment]
It would give options though for a script without having to do as much work. There can't be that many planets out there starting with numbers

**Comment by dmcbride** [comment]
There are 9 planets whose names start with #.  None of them are currently owned / colonised.

Personally, I'd rather the server start taking names in addition to IDs (and, eventually, instead of IDs).  This would eliminate all the ID lookup that scripts have to do, and, eventually, stop exposing everyones' IDs to everyone else.

**Comment by icydee** [comment]
using IDs is preferred, since scripts would need to be updated whenever a name change occurred and forgetting it would cause problems.

**Comment by RedOrion** [comment]
Concur, I don't really see a problem with having ID's public.

**Comment by dmcbride** [comment]
Exposing your IDs to you, I don't have a problem with (which may mean not "instead of IDs" *in all cases*, I'm going to blame this flu or whatever I've had this week for lacking that clarification).  Exposing your IDs to everyone else is what I'd like to avoid.  So, looking up an empire's information should use the empire's name, not ID, because it's not yours (being able to track players through name changes shouldn't be so trivial, IMO).  Looking up your building on your planet can (and probably has to) be done via ID, but it's yours, so that's fine.  Sending an attack fleet to / firing the BFG at a planet, uses name or location because it's not yours.  Pushing ships to your planet / your alliance's station can use ID or name because it's yours.

**Comment by RedOrion** [comment]
Something that might be best implemented now that we have we show the ID's in different areas

**Comment by tmtowtdi** [comment]
Closing because TLE is dead.
