### ISSUE TITLE
Poor choosing method for Saben planet destruction

### ISSUE THREAD

**Issue by lemming552** [plainblack/Lacuna-Server-Open#399]
Should choose a random body that fits criteria without hitting BHG neutralized.
Right now looks like it picks the same group everytime to check which will result in bottom portions of zones being turned to asteroids first.

**Comment by Imzogelmo** [comment]
For those not familiar with the issue: 
Saben regularly select planets to turn into asteroids. That's always been part of their *modus* *operandi*. And they always pick a planet from the same zone they are in. The problem is, less populated zones, or those who have traditionally been less populated, have had this activity go on for so long unopposed that the number of asteroids is getting quite high. 

This would be fine, but since the Saben's selection scheme seems to look only through the first few rows of a list sorted by the zone, indexed on the planet id, it causes a very un-random distribution of asteroids, due to the fact that body ids usually generate from the bottom up.

**Comment by dmcbride** [comment]
I think I'll take this one on.  By joining with star and then laws, I think we can use two queries to pull a very random body out of the hat.

The first query is a count, the second one is a random item from the full list using, I expect, `offset => $random_row_num, rows => 1`
