### ISSUE TITLE
Trades lose resources

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Server-Open#69]
On numerous occasions, people purchase a trade for resources and they arrive, are visible for a short while, then they disappear. 

After much thought I am certain that this is due to the interaction between the back-end scripts (hourly tick planets) and the front end UI code.

For example:-
 * back end code obtains a 'body'  object
 * front end code notes that a ship has arrived, obtains a 'body' object.
 * front end code updates the body resources.
 * back end code completes, updates the 'body' object.

the final back end update will effectively overwrite the 'body' object negating the update caused by the front end.

This is most likely to happen with people who are closely watching their ship arrivals in their browser, concerned perhaps about previously failed arrivals.

The solution is much more difficult to find.

Transactions might work, but would be a very big change to the structure of the code base.

Making the resource updates 'atomic' might help, but it would be a big change to identify all resource calculations.

I sort of think that doing planet 'tick's in a job queue might work but I don't know how big a change this would entail.

so, more thought is required unless there are other suggestions?

**Comment by dmcbride** [comment]
After modifying tick_planets.pl to not grab every planet object at the start (the way DBIx::Class handles the query can create excess objects before we need them), but only the IDs of the planets we're going to tick, and then loading each planet as we go, I think this may be mostly fixed.  Instead of holding all the objects around for 5 minutes or however long the tick takes, each body is only held for as long as it takes to tick that body.  This reduces the window of opportunity for this type of an error drastically to the point where it can be nearly ignorable.

A better fix, in my mind, is to override stuff in DBIx::Class so that some fields are not updated by setting directly, but by using SQL math.  i.e., instead of `SET bean_stored = ?`, use `SET bean_stored = bean_stored + ?` and provide the expected delta.  This gets complicated for foods/ores more than water/energy only because with water/energy we can cap it easily: `SET water_stored = LEAST(water_stored + ?, water_capacity)`, but food and ore will get convoluted here.  Not to mention general convolutionism when we try to get DBIx::Class to change how it operates for some fields in the first place.
